graphql-mocks/graphql-mocks

- src/mirage/wrappers/patch-auto-unions-interfaces.ts
- src/resolver-map/each-type.ts
- tests/integration/mirage-auto-resolver.test.ts
- tests/unit/mirage/wrappers/patch-auto-unions-interfaces.test.ts
- tests/unit/resolver-map/each-type.test.ts
Anything that is a widespread dependency should be passed into the pack dependencies. This PR fixes a leftover graphql schema dependency on `eachType` that can use the `graphqlSchema` conventional dependency that other wrappers depend on, too.
> Use graphqlSchema from pack dependency on eachType

- src/log/wrapper.ts
- src/mirage/wrappers/patch-auto-types.ts
- src/mirage/wrappers/patch-auto-unions-interfaces.ts
- src/performance/wrapper.ts
- src/resolver-map/pack.ts
- src/resolver-map/patch-each-field.ts
- src/resolver-map/wrap-each-field.ts
- src/resolver/wrap-in-map.ts
- src/resolver/wrap.ts
- src/spy/wrapper.ts
- src/stash-state/wrapper.ts
- src/types.ts
- src/utils.ts
- tests/mocks.ts
- tests/unit/log/wrapper.test.ts
- tests/unit/performance/wrapper.test.ts
- tests/unit/resolver-map/wrap-each.test.ts
- tests/unit/resolver/wrap-in-map.test.ts
- tests/unit/resolver/wrap.test.ts
- tests/unit/spy/wrapper.test.ts
- tests/unit/stash-state/wrapper.test.ts
Adds a lower level wrapper for just resolvers. This can be used directly via `resolver/wrap` or more easily with the `resolver/wrap-in-map` which is compatible directly for adding one-off resolvers in a resolver map with resolver wrappers.
> Add resolver field wrappers

- package.json
- src/graphql/handler.ts
- src/graphql/index.ts
- src/graphql/utils.ts
- src/index.ts
- src/resolver-map/pack.ts
- src/types.ts
- test/integration/mirage-auto-resolver.test.ts
- test/integration/mirage-context-resolvers.test.ts
- test/integration/test-helpers/executable-schema.ts
- test/integration/test-helpers/test-schema.ts
- test/unit/graphql/handler.test.ts
- yarn.lock
Provide an out-of-the-box query execution handler while support Resolver Map Middlewares. The goal is to help get people up and running with a query faster than having to rely on `pack` and wire things up themselves.
> Add a GraphQL Handler

- package.json
`graphql-test-resolvers` was an early name during development and ended up causing more confusion that it helped, so I decided to name it simply `graphql-mocks` as it was available 🤷.
> Rename to graphql-mocks

- src/graphql/handler.ts
- src/graphql/index.ts
- src/graphql/types.ts
- src/graphql/utils.ts
- src/mirage/middleware/patch-auto-field-resolvers.ts
- src/mirage/middleware/patch-auto-type-resolvers.ts
- src/pack/index.ts
- src/pack/pack.ts
- src/pack/types.ts
- src/pack/utils.ts
- src/resolver-map/embed.ts
- src/resolver-map/index.ts
- src/resolver-map/reference/target-reference.ts
- src/resolver-map/utils.ts
- src/resolver/extract-dependencies.ts
- src/types.ts
- test/integration/mirage-auto-resolve-object-types.test.ts
- test/integration/mirage-auto-resolve-root-query.test.ts
- test/integration/mirage-auto-resolver.test.ts
- test/integration/mirage-relay.test.ts
- test/integration/mirage-static-resolvers.test.ts
- test/mocks.ts
- test/unit/graphql/handler.test.ts
- test/unit/pack/utilts.test.ts
- test/unit/resolver-map/pack.test.ts
- test/unit/resolver/extract-dependencies.test.ts
* Move `pack` to its own top-level module
* Clean up implementation of the `graphql/handler` and abstract away parts into util functions
* Add a couple of extra tests
* Expose more on the GraphQL handler included the copied Schema that has the resolvers attached (executable)
* Expose the middlewares used
* Expose the final packed Resolver Map
* Expose pack dependencies
* Expose pack state
* `query` handler now allows for `GraphQLArgs` overrides on the 3rd object if there is any handler defaults that should be overridden
> 👐🏽 Tweak built-in GraphQL Handler

- src/graphql/handler.ts
- src/graphql/types.ts
- test/integration/mirage-auto-resolve-object-types.test.ts
- test/integration/mirage-auto-resolve-root-query.test.ts
- test/integration/mirage-auto-resolver.test.ts
- test/integration/mirage-relay.test.ts
- test/integration/mirage-static-resolvers.test.ts
- test/unit/graphql/handler.test.ts
The resolverMap as a first arg is not always required for `createGraphQLHandler` like it is for `pack`. If it was not used in `createGraphQLHandler` the first argument ends up being an empty object which doesn't read well. With it being optional, and included in the options hash, it allows for it to be specified only when needed. This API results in a cleaner usage.
> Move resolverMap into createGraphQLHandler options

- src/graphql/handler.ts
- src/graphql/index.ts
- src/graphql/types.ts
- src/graphql/utils.ts
- src/index.ts
- src/pack/types.ts
- src/pack/utils.ts
- src/resolver/extract-dependencies.ts
- src/types.ts
- test/integration/mirage-auto-resolve-object-types.test.ts
- test/integration/mirage-auto-resolve-root-query.test.ts
- test/integration/mirage-auto-resolver.test.ts
- test/integration/mirage-relay.test.ts
- test/integration/mirage-static-resolvers.test.ts
- test/unit/graphql/handler.test.ts
- test/unit/resolver/extract-dependencies.test.ts
In the future the handler will have additional state and a class sets up for hooks and lifecycle methods.
* Changes the creation of the handler to a class and makes it synchronous
* The async operation of packing is deferred until the first query
* Add managed context including the spreading initial and query contexts
> Switch to class-based GraphQL Handler

- .github/workflows/main.yml
- package.json
- src/graphql/handler.ts
- src/mirage/route-handler.ts
- src/mirage/types.ts
- src/relay/utils.ts
- test/integration/test-helpers/pretender.ts
- test/unit/mirage/route-handler.test.ts
If already mocking with Mirage JS in a browser then this route handler can setup `graphql-mocks` quickly with `createRouteHandler`. It takes either a `GraphQLHandler` instance or the options that would create an instance.
Within a route handler the server instance is `this` so it's easy to specify the `mirageServer` dependency:
```ts
const mirageServer = createServer({
routes() {
this.post(
'graphql',
createRouteHandler({
resolverMap,
dependencies: {
// pass in mirage server dependency
mirageServer: this,
graphqlSchema,
},
}),
);
},
});
```
> 🏝👋🏽 Add mirage route handler 

- src/mirage/mapper/mapper.ts
- test/unit/mirage/mapper/mapper.test.ts
When creating a field mapping the type and model are also specified. The mapping between these are likely also needed in most cases. In the future, it may be necessary to have a way of overriding, or opting out of this additional mapping.
> 🗺 Include Type/Model mapping in field mapping

- src/mirage/index.ts
- test/unit/mirage/route-handler.test.ts
It'd be commonly used so better to exported directly from `graphql-mocks/mirage`.
> 🔝 Export createRouteHandler from graphql-mocks/mirage

- src/mirage/resolver/interface.ts
- src/mirage/resolver/object.ts
- src/mirage/resolver/root-query.ts
- src/mirage/resolver/union.ts
- src/mirage/resolver/utils.ts
- test/unit/mirage/resolvers/interface.test.ts
- test/unit/mirage/resolvers/union.test.ts
- yarn.lock
A few small mirage tweaks
* Bump miragejs in `yarn.lock`
* Improve error messages for union and interface resolvers
* Use graphql built-in helper for finding possible types for interface
* Safely pulling models from mirage in root resolver (for cases like when the db has been tampered with and things blow up)
> 🏝️🧑‍🔧 Small mirage tweaks

- src/mirage/resolver/abstract.ts
- src/mirage/resolver/utils.ts
- test/unit/mirage/resolvers/abstract.test.ts
* Improves on the outline and different methods of the Mirage JS Abstract Type Resolver
* Adds __typename checks
* Simplifies tests into specific test cases
* A few tweaks to the error messages
> Improve abstract type resolver

- src/resolver-map/index.ts
- src/resolver-map/layer.ts
- test/unit/resolver-map/layer.test.ts
Adding the `layer` middleware helps in a few ways. Unlike `embed` which focuses on a single resolver and applying it in many places via highlighting, `layer` focuses on a _chunk of different but very specific resolvers_ being spread into a resolver map. These _resolver map partials_ can be kept separate and folded into each other as needed for various test cases and scenarios.
For example
```js
layer([
unauthenticatedResolvers,
trialAccountResolvers,
], { replace: true, wrappers: [logWrapper] });
```
where `unauthenticatedResolvers` and `trialAccountResolvers` would consist of specific resolver partials that would setup the conditions for those cases, while also replacing existing resolvers and adding a `logWrapper`.
> 🍰 Add the layer middleware

- packages/graphql-mocks/src/highlight/utils/build-reference-map.ts
- packages/graphql-mocks/src/resolver/apply-wrappers.ts
- packages/graphql-mocks/src/resolver/constants.ts
- packages/graphql-mocks/src/resolver/create-wrapper.ts
- packages/graphql-mocks/src/resolver/types.ts
- packages/graphql-mocks/test/unit/resolver/create-wrapper.test.ts
> Enums are one of the few features TypeScript has which is not a type-level extension of JavaScript.
To improve the experience provided by typings the one enum in use is being converted to a `const` object. This allows people to easily use the string representation instead of having to reference the enum.
```js
import WrapperFor from '...'
createWrapper('namedWrapper', WrapperFor.TYPE, wrapperFn);
```
to *also* allowing just using the string const directly:
```js
import WrapperFor from '...'
createWrapper('namedWrapper', "TYPE", wrapperFn);
```
The choices would still autocomplete.
This is more flexible and creates an output closer to pure javascript without the complexities and exceptions around enums in typescript, but is technically less accurate.
> Remove the single enum in use

- packages/graphql-mocks/src/resolver/apply-wrappers.ts
- packages/graphql-mocks/src/resolver/create-wrapper.ts
- packages/graphql-mocks/src/resolver/types.ts
- packages/graphql-mocks/test/unit/resolver/create-wrapper.test.ts
This will provide better type inference around using `applyWrappers` and `createWrapper` by expanding on the `NamedWrapper` type to be more specific by providing a type argument.
> Improve wrapper typings

- packages/docs/.babelrc
- packages/docs/.mocharc.yaml
- packages/docs/babel.config.js
- packages/docs/scripts/register-babel-for-tests.js
- packages/graphql-mocks/src/graphql/utils/create-schema.ts
- packages/graphql-mocks/src/highlight/highlighter/reference.ts
- packages/graphql-mocks/src/highlight/utils/walk.ts
- packages/graphql-mocks/src/relay/paginate-nodes.ts
- packages/graphql-mocks/src/relay/wrapper.ts
- packages/graphql-mocks/src/resolver-map/embed.ts
Rollup had warnings related to a few circular dependencies. It didn't appear that these caused any issues but it was easy enough to clean up. The `babel.rc` file was converted to a `babel.config.js` as referenced in the Docusaurus docs, this along with `@babel/plugin-transform-modules-commonjs`, might fix bundling issues with the homepage graphiql example. The `.babelrc` configuration values that was there before was still needed for tests and was moved to the arguments directly for `babel-register`.
> Clean up circular dependencies

- packages/graphql-mocks/package.json
- packages/mirage/package.json
- packages/network-nock/package.json
- packages/paper/package.json
- packages/sinon/package.json
- templates/new-package/package.json
- templates/new-package/rollup-watch.config.js
- templates/new-package/rollup.config.js
- templates/new-package/scripts/copy-scrubbed-pjson.js
- templates/new-package/test/tsconfig.json
- templates/new-package/test/unit/index.test.ts
- templates/new-package/tsconfig.json
When a package hasn't been published before **and** it's scoped `@graphql-mocks/*` lerna will fail to publish. This pull request adds `"access": "public"` to the `publishConfig` for existing packages and includes it in the new package template. The new package will help with the boilerplate of starting new packages 🕺
> Add new-package starter template

- packages/docs/docs/paper/mutating-data.md
Fix broken operation api links to be considered external so that they're not intercepted by the docusaurus router.
> Update operation api links

- CHANGELOG.md
- package.json
- scripts/create-release.js
- scripts/tag-releases.js
- yarn.lock
This pull request improves the create-release script to:
* Run tests and find breaking changes with peer dependencies and then update peer dependency ranges
* Pull changelog entries from pull requests in the format of:
````markdown
```markdown changelog(graphql-mocks)
Testing changelog entry for package graphql-mocks. The package name in the parens specify which package the changelog entry is assigned to.
```
````
Fixes #70
> Improve create-release script 

- .github/pull_request_template.md
Since adding changelog support to the `create-release` script it is helpful to have the pull request template to take care of some of the boilerplate.
> Add pr template to make use of new changelog feature

- scripts/create-release.js
After some testing it turns out the package.json wasn't being reloaded after lerna version bumping. This caused versio bumps to be overwritten with the original package.json and miss out on the new version and any peer dependency fixes. 
This bug was the result of loading the package.json using the `require` from node which caches the result. Instead of messaging with the cache system the loading of packge.json now loads directly from disk using the `fs` module.
> Fix create-release script

- packages/cli/.gitignore
- packages/cli/package.json
- yarn.lock
Previously the scripts referenced `oclif-dev` which is no longer included as part of the newer oclif version, the previous `oclif-dev` commands have been collapsed into the `oclif` cli. This pull request adds the `oclif` cli and updates the scripts previously using `oclif-dev`.
```markdown changelog(gqlmocks)
* (fix) include `oclif` dependency for buildings
```
> Add oclif dependency for the cli

- CONTRIBUTING.md
- DEVELOPMENT.md
- README.md
- packages/cli/package.json
- packages/docs/.gitignore
- packages/docs/docusaurus.config.js
- packages/docs/src/pages/packages.jsx
- packages/faker/README.md
- packages/faker/package.json
- packages/graphql-mocks/README.md
- packages/graphql-mocks/package.json
- packages/mirage/README.md
- packages/mirage/package.json
- packages/network-express/README.md
- packages/network-express/package.json
- packages/network-msw/README.md
- packages/network-msw/package.json
- packages/network-nock/README.md
- packages/network-nock/package.json
- packages/paper/README.md
- packages/paper/package.json
- packages/sinon/README.md
- packages/sinon/package.json
- scripts/create-release.js
- templates/new-package/README.md
To improve discoverability across the project this pull request adds links to the packages source code, npm page, and api documentation. It also adds READMEs in each package so there is content published with the package for anyone searching from the npm side.
Fixes #69 
```markdown changelog(graphql-mocks)
* (feature) Added package README
```
```markdown changelog(graphql-paper)
* (feature) Added package README
```
```markdown changelog(@graphql-mocks/sinon)
* (feature) Added package README
```
```markdown changelog(@graphql-mocks/network-express)
* (feature) Added package README
```
```markdown changelog(@graphql-mocks/network-nock)
* (feature) Added package README
```
```markdown changelog(@graphql-mocks/network-msw)
* (feature) Added package README
```
```markdown …
```
> Update READMEs and package documentation

- packages/cli/test/commands/serve.test.ts
- packages/docs/package.json
- packages/graphql-mocks/package.json
- packages/graphql-mocks/src/highlight/highlight.ts
- packages/graphql-mocks/src/highlight/highlighter/resolves-to.ts
- packages/graphql-mocks/src/highlight/operation/exclude.ts
- packages/graphql-mocks/src/highlight/utils/unique.ts
- packages/graphql-mocks/src/pack/pack.ts
- packages/graphql-mocks/src/resolver-map/layer.ts
- packages/mirage/package.json
- packages/mirage/src/utils.ts
- packages/paper/package.json
- yarn.lock
Using es-first modules helps when it comes to being more compatible with browsers and supporting _The Future Way™️_.
Using `ramda` instead of `lodash-es` because `ramda` supports esmodules and commonjs modules from a single package (specifically important for node which was throwing errors about the `type="module"` in `lodash-es`).
Fixes #169 
Supersedes #171 
```markdown changelog(graphql-mocks)
* (fix) Replace individual `lodash.*` packages with singular `ramda`
```
```markdown changelog(graphql-paper)
* (fix) Replace individual `lodash.*` packages with singular `ramda`
```
```markdown changelog(@graphql-mocks/mirage)
* (fix) Replace individual `lodash.*` packages with singular `ramda`
```
> Migrate from lodash to ramda

- packages/docs/docs/network/introducing-network-handlers.md
Seemed helpful to add `gqlmocks serve` command to the Network Handling docs as it fulfill this role of combining mocks with a network interface.
> Add `gqlmocks serve` command to network handler docs

- packages/docs/docs/resolver/available-wrappers.md
- packages/graphql-mocks/src/wrapper/index.ts
- packages/graphql-mocks/src/wrapper/latency.ts
- packages/graphql-mocks/test/unit/wrapper/latency.test.ts
As in *The Real World :tm:* some resolvers may take longer than others due to their complexity or some async task that might be performed within them. This pull request adds a latency wrapper to be able to delay resolvers by some latency in milliseconds (either a specific number `1000` or a random number within a range `[1000, 1500]`).
Closes #64.
```markdown changelog(graphql-mocks)
* (feature) Added latency wrapper for delaying resolvers with specified latency
```
> Add latency wrapper

- packages/docs/docs/resolver/available-wrappers.md
- packages/graphql-mocks/src/wrapper/debugger.ts
- packages/graphql-mocks/src/wrapper/index.ts
Adds a debugger wrapper that can be used for adding quick `debugger` before/after resolvers
Closes #65.
```markdown changelog(graphql-mocks)
* (feature) Add a debugger wrapper that adds debuggers before and/or after resolver execution
```
> Add debugger wrapper

- packages/browser-acceptance-tests/package.json
After going to do a publish of packages with lerna, it was clear that `browser-acceptance-tests` internal package for testing browser network adapters was missing a `private: true` flag 🙈
> Make browser-acceptance-tests a private package

- packages/docs/docs/network/introducing-network-handlers.md
- packages/docs/package.json
- packages/docs/sidebars.js
- packages/docs/src/pages/packages.jsx
Link up a few things on the documentation site for `@graphql-mocks/network-cypress` so that it's available in the sidebar and in the API and Packages section. Closes #209
> Link up documentation for @graphql-mocks/network-cypress

- packages/cli/test/commands/serve.test.ts
Add test related to the core fix for gqlmocks serve command in #211.
> Add test for cors fix in gqlmocks serve command

- packages/paper/src/paper.ts
- packages/paper/test/unit/paper.test.ts
This PR adds a `clear` method to the `Paper` to purge all stored documents. This functionality is useful for resetting the store after each test to prevent cross-test data dependencies.
related issue: #206 
```markdown changelog(graphql-paper)
* (feature) Add `clear` method for purging all documents and resetting history
```
> feat: add `clear` method to graphql-paper

- DEVELOPMENT.md
Getting issues when running `yarn`, as a note i got v14 is min version to set this up.
> Update node required version in documentation

- packages/cli/package.json
- packages/cli/src/commands/serve.ts
- yarn.lock
Make either `--handler` or `--schema` flag required instead of both. This pull request also manually applies the falso middleware to either the in memory graphql handler created *or* by patching it into the `middlewares` array from the handler loaded by path.
```markdown changelog(gqlmocks)
* (fix) Make `serve` command work with either `--handler` or `--schema` flag instead of both being required
* (fix) Allow false middleware via `--fake` on serve command to be applied to a handler specified by path
```
> Improve cli `serve` command flags

- .github/workflows/main.yml
- package.json
- packages/cli/package.json
- packages/docs/code-examples/home/handler.source.js
- packages/docs/docusaurus.config.js
- packages/docs/package.json
- packages/docs/src/pages/index.jsx
- packages/falso/package.json
- packages/graphql-mocks/package.json
- packages/mirage/package.json
- packages/network-cypress/package.json
- packages/network-express/package.json
- packages/network-msw/package.json
- packages/network-nock/package.json
- packages/network-pretender/package.json
- packages/paper/package.json
- packages/sinon/package.json
- templates/new-package/package.json
- yarn.lock
Bumps from Node to 14 to 16 across all packages. It also gets rid of the  `event-target-polyfill` as it's no longer needed as of Node 15. One thing that was caught with tests though is that Node's native usage of `EventTarget` and `Event` is that any event has to be an instance of `Event` and not a subclass.
```markdown changelog(graphql-paper)
* (breaking) Bump from Node 14 to 16
```
```markdown changelog(gqlmocks)
* (breaking) Bump from Node 14 to 16
```
```markdown changelog(graphql-mocks)
* (breaking) Bump from Node 14 to 16
```
```markdown changelog(@graphql-mocks/falso)
* (breaking) Bump from Node 14 to 16
```
```markdown changelog(@graphql-mocks/network-cypress)
* (breaking) Bump from Node 14 to 16
```
```markdown changelog(@graphql-mocks/network-pretender)
* (breaking) Bump from …
```
> Bump to node 16

- packages/docs/docs/highlight/available-highlighters.md
- packages/falso/package.json
- packages/falso/src/falso-middleware.ts
- packages/falso/test/integration/faker-middleware.test.ts
- packages/graphql-mocks/src/highlight/highlighter/interface-field.ts
- packages/graphql-mocks/src/highlight/highlighter/interfaces.ts
- packages/graphql-mocks/src/highlight/index.ts
- packages/graphql-mocks/test/unit/highlight/highlighter/interface-field.test.ts
Fixes the issue where interface types and fields were being picked up by the falso middleware and it was trying to attach a field resolver. By adding a new highlighter for interface fields these can be excluded so that the middleware only installs a field resolver for object types.
Fixes #167
```markdown changelog(graphql-mocks)
* (feature) Add a new `interfaceField` highlighter for highlighting interfaces with fields. This is different from the `interfaces`  highlighter which returns only the interfaces typenames themselves (for type resolvers). See highlighter documentation for more information.
```
```markdown changelog(graphql-mocks)
* (fix) Fix falso middleware handling around automatic faking with unions and interfaces
```
> Fix falso middleware handling of abstract types (interfaces and unions)

- packages/graphql-mocks/src/highlight/utils/unique.ts
Previously the `unique` highlight helper would use `equals` ramda for highlight reference comparisons. Turns out this is a very expensive way of comparing references _and_ this library already had a `isEqual` helper for comparing references that is much faster (and could possibly still be improved some).
This pull request swaps the ramda `equals` for the local library highlight reference comparison helper `isEqual`.
```
PerformanceMeasure {
duration: 3987.551749944687
}
```
```
PerformanceMeasure {
duration: 107.58137512207031
}
```
The improvement is ~36x which is both great but also kind of unfortunate it wasn't caught before. The test used the `falsoMiddleware` and a schema with 200 types and 10 fields per type.
(Likely) fixes #226 
```markdown changelog(graphql-mocks)
* (feature) …
```
> Use local reference `isEqual` helper for references instead of ramda equals

- packages/docs/docs/handler/using-custom-scalars.md
- packages/docs/sidebars.js
- packages/graphql-mocks/src/graphql/handler.ts
- packages/graphql-mocks/src/graphql/type-utils/is-scalar-definition.ts
- packages/graphql-mocks/src/graphql/types.ts
- packages/graphql-mocks/src/graphql/utils/attach-scalars-to-schema.ts
- packages/graphql-mocks/src/graphql/utils/index.ts
- packages/graphql-mocks/src/types.ts
- packages/graphql-mocks/test/unit/graphql/handler.test.ts
- packages/graphql-mocks/test/unit/graphql/utils.test.ts
- packages/graphql-mocks/test/unit/wrapper/latency.test.ts
This pull request adds support for custom scalars. These are added to the `GraphQLHandler` via a _Scalar Map_.
Roughly, it looks something like this.
```js
import dateScalar from 'graphql-date-scalar'; // example package
const scalarMap = {
Date: dateScalar
};
const handler = new GraphQLHandler({
scalarMap,
// ...
});
```
The pull request includes documentation with more examples and references.
```markdown changelog(graphql-mocks)
* (feature) Add support for custom scalars
```
> Add custom scalar support

- package.json
- packages/cli/package.json
- packages/cli/src/hooks/init.ts
- packages/cli/src/lib/config/load-config.ts
- packages/cli/test/commands/config/generate.test.ts
- yarn.lock
`gqlmocks` supports loading the `.ts` file format. It does this through an `init` hook. The `init` hook uses `@babel/register` so that every file being imported via  node `require` can be  transpiled on the fly. By using `@babel/preset-env` and `@babel/preset-typescript` this enables support for a wide variety features including transpiling module syntax (esmodules -> commonjs) and remove typescript type definitions, to try and ensure strong compatibility.
This pull request does two things:
1. Sets up oclif so that this hook actually gets called
2. Ensures that files outside of the current working directory can be included in transpilation
It was tested against the `./bin/run config generate` command locally after doing a fresh `yarn build`. Using `./bin/dev` would not show the bug …
> Fix gqlmocks cli dynamic handling of typescript files

- packages/cli/README.md
- packages/cli/package.json
The oclif readme command was being ran during prepack which means the README was lagging in being committed and used during the build process. This matters for the website that uses the committed and generated README.
> Fix cli readme generation to happen during the build process

- packages/falso/package.json
- packages/graphql-mocks/package.json
- packages/mirage/package.json
- packages/network-cypress/package.json
- packages/network-express/package.json
- packages/network-msw/package.json
- packages/network-nock/package.json
- packages/network-playwright/package.json
- packages/network-pretender/package.json
- packages/paper/package.json
- packages/sinon/package.json
- scripts/check-exports-map.js
- scripts/copy-scrubbed-pjson.js
Fixes issue reported in #259
```markdown changelog(graphql-mocks)
* (fix) Fixed typescript `types` references in package.json
```
```markdown changelog(graphql-paper)
* (fix) Fixed typescript `types` references in package.json
```
```markdown changelog(@graphql-mocks/falso)
* (fix) Fixed typescript `types` references in package.json
```
```markdown changelog(@graphql-mocks/mirage)
* (fix) Fixed typescript `types` references in package.json
```
```markdown changelog(@graphql-mocks/network-cypress)
* (fix) Fixed typescript `types` references in package.json
```
```markdown changelog(@graphql-mocks/network-express)
* (fix) Fixed typescript `types` references in package.json
```
```markdown changelog(@graphql-mocks/network-msw)
* (fix) Fixed typescript `types` references in package.json
``` …
> Fix package json types references

- packages/graphql-mocks/src/graphql/utils/build-context.ts
- packages/graphql-mocks/src/pack/pack.ts
- packages/graphql-mocks/src/resolver-map/embed.ts
- packages/graphql-mocks/src/resolver-map/layer.ts
- packages/graphql-mocks/test/mocks.ts
- packages/graphql-mocks/test/unit/graphql/handler.test.ts
- packages/graphql-mocks/test/unit/pack/pack.test.ts
- packages/graphql-mocks/test/unit/pack/utils.test.ts
- packages/graphql-mocks/test/unit/resolver-map/embed.test.ts
- packages/graphql-mocks/test/unit/resolver-map/layer.test.ts
This pull request moves the management of adding of the `pack` property on context _from_ the **`pack` function** _to_ the `embed` and `layer` middlewares.
The main reason to remove the application of `embedPackOptionsWrapper` during the **`pack` function** is because it unnecessarily wraps *every. single. resolver.* with a wrapper that intercepts context and ensures `pack` is included. Wrapping every single resolver at pack-time (usually on first query) is a huge unnecessary slow down with large schemas. This was discovered in #272. 
By moving this "managed context" protection to the `layer` and `embed` middleware implementations (the two ways of applying wrappers with graphql-mocks) it means it is more closely guarding against other wrappers at the place where wrappers are applied. Only …
> Improve managed context of `pack` property

- packages/graphql-mocks/src/graphql/utils/attach-scalars-to-schema.ts
- packages/graphql-mocks/test/unit/utils/attach-scalars-to-schema.test.ts
Simplifies the implementation of `attachScalarsToSchema` by using one main iteration instead of four separate iterations assigned with intermediate variables. Instead of skipping over scalars that don't match it throws errors which would probably save time debugging other errors like typos or malformed scalar definitions.
```markdown changelog(graphql-mocks)
* (feature) Simplify implementation of `attachScalarsToSchema`
```
> Simplify implementation of `attachScalarsToSchema`

- packages/graphql-mocks/src/graphql/handler.ts
- packages/graphql-mocks/src/graphql/resolver-router.ts
- packages/graphql-mocks/test/unit/graphql/handler.test.ts
- packages/graphql-mocks/test/unit/wrapper/latency.test.ts
This pull request aims to increase performance a bit by skipping attaching every resolver from a resolver map to schema types, and instead have a _resolver router_. The resolver router will lookup a resolver based on the current resolver info and pass along the same arguments it received. There is a separate field and type resolver routers. 
```markdown changelog(graphql-mocks)
* (feature) Use routing resolvers instead of attaching resolvers directly to schema types
* (feature) `GraphQLHandler#pack` is now public. Previously this was done internally to "pack together" all the resolver map middlewares, and because it was async it was deferred to the first query. With it being a public method on `GraphQLHandler it can be called earlier so that the first query isn't slowed down
```
> Replace resolver attaching to schema with resolver routers

- packages/graphql-mocks/src/highlight/highlight.ts
- packages/graphql-mocks/src/highlight/highlighter/field.ts
- packages/graphql-mocks/src/highlight/utils/convert-highlighter-or-reference-to-highlighter.ts
- packages/graphql-mocks/src/highlight/utils/reference-set-helpers.ts
More highlight improvements, as a follow up to #274
Performance improvements in this PR:
* `clone` was a silly way of making an array with the same references as an existing array. This was hugely expensive.
* Added early returns where work could be avoided
* Use less array functions to avoid creating new arrays over and over when a single `for` iteration will do
```markdown changelog(graphql-mocks)
* (feature) Further performance improvements of highlighting and highlighters
```
> Highlight performance improvements

- packages/graphql-mocks/src/highlight/highlighter/field.ts
Ran into a `RangeError: Maximum call stack size exceeded with array.push(...)` locally with some performance testing with a _very_ large schema. Spreading an array as arguments pushes it on to the stack and ends up maxing out the call for `push`.
```markdown changelog(graphql-mocks)
* (fix) Fix "RangeError: Maximum call stack size exceeded" by avoiding spreading large list of highlight references
```
> Avoid array.push with spread of large array of arguments
